# Site settings
title: Jonathan Mathews
header-img: "http://res.cloudinary.com/jonmathews-com/image/upload/q_32/v1433691011/home-bg_lk6xjf.jpg"
email: jdmathews@gmail.com
description: "Jonathan Mathews | Product Manager"
baseurl: ""
url: "http://jonmathews.com"
twitter_username: jonmathews
github_username:  jonmathews
linkedin_url: "http://www.linkedin.com/in/jonathanmathews1"
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
